spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ticketing?rewriteBatchedStatements=true&serverTimezone=UTC
    username: ticketing
    password: ticketing
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
